apiVersion: v1
kind: Service
metadata:
  name: nginx-services
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007     # Fixed port on each Node’s IP
  type: NodePort
  # type: LoadBalancer